#!/usr/bin/env bash
# scripts/published-smoke.sh — published-artifact smoke harness.
#
# Sibling to scripts/smoke-v0.7.sh. That script validates correctness
# against the *in-tree* workspace (runtime scenarios against local
# fixtures). This script validates that the *published crates.io
# artifacts* for a given version resolve + compile + expose the
# expected public surface from a clean consumer perspective.
#
# Rationale: per CLAUDE.md §5 (release gate items 3, 5, 8) and
# feedback_smoke_before_release.md, "in-workspace tests miss
# external-consumer breakage". v0.3.2 shipped a #[non_exhaustive]
# type with no constructor that only surfaced when a scratch consumer
# tried to build against the published artifact; v0.6.0 shipped a
# broken read_summary for the same reason. This script provides a
# reusable, scripted equivalent of the ad-hoc /tmp Cargo.toml probe
# used for v0.8.1's manual smoke, so every release runs the same
# gate.
#
# Usage:
#   bash scripts/published-smoke.sh <VERSION>
#
#   e.g. bash scripts/published-smoke.sh 0.9.0
#
# What it checks:
#   1. The umbrella `flowfabric` crate at <VERSION> resolves from
#      crates.io together with ff-sdk, ff-core, ff-backend-valkey,
#      ff-backend-postgres at the same version.
#   2. The default-feature build (`valkey` on) compiles a consumer
#      main that references the v0.9 consumer-facing additions:
#        - flowfabric::sdk::ClaimGrant                      (#283)
#        - flowfabric::core::backend::PrepareOutcome        (#281)
#        - flowfabric::core::contracts::SeedWaitpointHmacSecretArgs (#280)
#        - flowfabric::core::contracts::LeaseSummary fields
#            .lease_id / .attempt_index / .last_heartbeat_at (#278)
#        - default feature `valkey` pulls ff-backend-valkey  (#279)
#   3. The postgres-only build (`default-features=false, features=["postgres"]`)
#      also resolves + compiles.
#
# Exit codes:
#   0 — all builds clean, all v0.9 symbols referenced
#   1 — build failed (version not on crates.io, symbol renamed, bad pin)
#   2 — script invocation problem (missing arg, scratch dir issue)

set -euo pipefail

if [[ $# -lt 1 || -z "${1:-}" ]]; then
    echo "usage: $0 <VERSION>    (e.g. $0 0.9.0)" >&2
    exit 2
fi

VERSION="$1"
TS="$(date +%s)"
SCRATCH="/tmp/ff-published-smoke-v${VERSION}-${TS}"

if ! mkdir -p "${SCRATCH}"; then
    echo "FAIL: could not create scratch dir ${SCRATCH}" >&2
    exit 2
fi

echo "==> published-smoke: version=${VERSION}"
echo "    scratch=${SCRATCH}"

# ------------------------------------------------------------------
# Variant A: default features (valkey on).
# ------------------------------------------------------------------

VALKEY_DIR="${SCRATCH}/valkey-default"
mkdir -p "${VALKEY_DIR}/src"

cat > "${VALKEY_DIR}/Cargo.toml" <<EOF
# Auto-generated by scripts/published-smoke.sh. Do not edit.
# Validates the published crates.io artifacts for flowfabric v${VERSION}
# under the default (valkey) feature set.
[package]
name = "ff-published-smoke-valkey"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
flowfabric = "=${VERSION}"
ff-sdk = "=${VERSION}"
ff-core = "=${VERSION}"
ff-backend-valkey = "=${VERSION}"
ff-backend-postgres = "=${VERSION}"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
EOF

cat > "${VALKEY_DIR}/src/main.rs" <<'EOF'
// Auto-generated by scripts/published-smoke.sh.
//
// This file exists to exercise compile-time resolution of the v0.9
// consumer-facing surface. It performs no network I/O, spawns no
// runtime, and is never expected to be executed. If any referenced
// symbol is renamed, removed, or re-pathed between the scripted
// VERSION and `main`, this file fails to compile and the release
// gate trips — which is the whole point.
//
// Symbol coverage (from scripts/published-smoke.sh):
//   - flowfabric::sdk::ClaimGrant                          (#283)
//   - flowfabric::core::backend::PrepareOutcome            (#281)
//   - flowfabric::core::contracts::SeedWaitpointHmacSecretArgs (#280)
//   - flowfabric::core::contracts::LeaseSummary fields
//       .lease_id / .attempt_index / .last_heartbeat_at    (#278)
//   - default feature `valkey` => ff-backend-valkey reachable (#279)

// Module-path probes: these imports fail at compile time if the
// umbrella re-export layout drifts.
#[allow(unused_imports)]
use flowfabric::{core, sdk, valkey};

#[allow(unused_imports)]
use flowfabric::core::backend::PrepareOutcome;
#[allow(unused_imports)]
use flowfabric::core::contracts::{
    ClaimForWorkerArgs, LeaseSummary, SeedWaitpointHmacSecretArgs,
};
#[allow(unused_imports)]
use flowfabric::sdk::ClaimGrant;

// Compile-time reachability: the closures are never invoked, but
// referencing the types forces monomorphization / resolution.
#[allow(dead_code)]
fn probe_claim_grant() -> impl Fn(ClaimGrant) -> ClaimGrant {
    |g| g
}

#[allow(dead_code)]
fn probe_prepare_outcome() -> impl Fn(PrepareOutcome) -> PrepareOutcome {
    |o| o
}

#[allow(dead_code)]
fn probe_seed_hmac_args() -> impl Fn(SeedWaitpointHmacSecretArgs) -> SeedWaitpointHmacSecretArgs {
    |a| a
}

#[allow(dead_code)]
fn probe_claim_for_worker_args() -> impl Fn(ClaimForWorkerArgs) -> ClaimForWorkerArgs {
    |a| a
}

// #278: LeaseSummary gained lease_id / attempt_index / last_heartbeat_at.
// Probing by field access (not construction — the struct is
// #[non_exhaustive] and must be built via LeaseSummary::new + setters).
#[allow(dead_code)]
fn probe_lease_summary_fields(summary: &LeaseSummary) {
    let _ = &summary.lease_id;
    let _ = &summary.attempt_index;
    let _ = &summary.last_heartbeat_at;
}

// #279: default feature `valkey` activates ff-backend-valkey. The
// `flowfabric::valkey` re-export only exists when that feature is on,
// so this use-statement already asserts default-features correctness.
#[allow(dead_code)]
fn probe_valkey_reexport() {
    // Touch the re-exported backend so the `valkey` feature path is
    // actually walked.
    let _ = std::any::type_name::<valkey::ValkeyBackend>;
    // Also confirm `core` re-export resolves by naming a type from it.
    let _ = std::any::type_name::<core::contracts::ClaimForWorkerArgs>;
}

fn main() {
    // Print resolved version for operator confirmation. env! is
    // evaluated at compile time against the scratch crate's own
    // Cargo.toml — not a network call.
    println!(
        "ff-published-smoke valkey-default: built against flowfabric {}",
        env!("CARGO_PKG_VERSION"),
    );
}
EOF

# ------------------------------------------------------------------
# Variant B: postgres-only (default-features off).
# ------------------------------------------------------------------

PG_DIR="${SCRATCH}/postgres-only"
mkdir -p "${PG_DIR}/src"

cat > "${PG_DIR}/Cargo.toml" <<EOF
# Auto-generated by scripts/published-smoke.sh. Do not edit.
# Validates the published crates.io artifacts for flowfabric v${VERSION}
# under --no-default-features + features=["postgres"] (RFC-012 agnostic
# posture).
[package]
name = "ff-published-smoke-postgres"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
flowfabric = { version = "=${VERSION}", default-features = false, features = ["postgres"] }
ff-sdk = { version = "=${VERSION}", default-features = false }
ff-core = "=${VERSION}"
ff-backend-postgres = "=${VERSION}"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1"
EOF

cat > "${PG_DIR}/src/main.rs" <<'EOF'
// Auto-generated by scripts/published-smoke.sh.
//
// Postgres-only variant: confirms the umbrella's
// default-features=false + features=["postgres"] path resolves and
// exposes ff-backend-postgres through `flowfabric::postgres`.

#[allow(unused_imports)]
use flowfabric::{core, postgres, sdk};

#[allow(unused_imports)]
use flowfabric::core::backend::PrepareOutcome;
#[allow(unused_imports)]
use flowfabric::core::contracts::{
    ClaimForWorkerArgs, LeaseSummary, SeedWaitpointHmacSecretArgs,
};

#[allow(dead_code)]
fn probe_postgres_reexport() {
    let _ = std::any::type_name::<postgres::PostgresBackend>;
}

#[allow(dead_code)]
fn probe_lease_summary_fields(summary: &LeaseSummary) {
    let _ = &summary.lease_id;
    let _ = &summary.attempt_index;
    let _ = &summary.last_heartbeat_at;
}

#[allow(dead_code)]
fn probe_prepare_outcome() -> impl Fn(PrepareOutcome) -> PrepareOutcome {
    |o| o
}

#[allow(dead_code)]
fn probe_seed_hmac_args() -> impl Fn(SeedWaitpointHmacSecretArgs) -> SeedWaitpointHmacSecretArgs {
    |a| a
}

#[allow(dead_code)]
fn probe_claim_for_worker_args() -> impl Fn(ClaimForWorkerArgs) -> ClaimForWorkerArgs {
    |a| a
}

fn main() {
    println!(
        "ff-published-smoke postgres-only: built against flowfabric {}",
        env!("CARGO_PKG_VERSION"),
    );
}
EOF

# ------------------------------------------------------------------
# Build both variants. Each `cargo build` resolves against crates.io.
# We intentionally use a per-variant CARGO_TARGET_DIR inside the
# scratch tree (via cd) so the two builds don't share artifacts — the
# feature-unification rules differ and cross-pollination would mask
# default-features bugs like #279.
# ------------------------------------------------------------------

VARIANT_A_OK=0
VARIANT_B_OK=0

echo "==> published-smoke: variant A (valkey default features)"
if ( cd "${VALKEY_DIR}" && cargo build --quiet ); then
    VARIANT_A_OK=1
    echo "    PASS: variant A built"
else
    echo "    FAIL: variant A build failed" >&2
fi

echo "==> published-smoke: variant B (postgres, no default features)"
if ( cd "${PG_DIR}" && cargo build --quiet ); then
    VARIANT_B_OK=1
    echo "    PASS: variant B built"
else
    echo "    FAIL: variant B build failed" >&2
fi

echo "=================================================================="
echo "published-smoke summary for v${VERSION}:"
echo "  scratch dir:            ${SCRATCH}"
if [[ "${VARIANT_A_OK}" -eq 1 ]]; then
    echo "  variant A (valkey):     PASS"
else
    echo "  variant A (valkey):     FAIL"
fi
if [[ "${VARIANT_B_OK}" -eq 1 ]]; then
    echo "  variant B (postgres):   PASS"
else
    echo "  variant B (postgres):   FAIL"
fi
echo "=================================================================="

if [[ "${VARIANT_A_OK}" -eq 1 && "${VARIANT_B_OK}" -eq 1 ]]; then
    echo "==> published-smoke: PASS"
    exit 0
else
    echo "==> published-smoke: FAIL" >&2
    exit 1
fi
